### ISSUE TITLE
Is it possible to get the video feed?

### ISSUE THREAD

**Issue by freaad** [microlinux/tello#2]
I am wondering that is it possible to get the video feeding or not 
using by sdk?

**Comment by anj-easyinspect** [comment]
No, it does not seem like it at the moment.
[https://dl-cdn.ryzerobotics.com/downloads/tello/0228/Tello+SDK+Readme.pdf](https://dl-cdn.ryzerobotics.com/downloads/tello/0228/Tello+SDK+Readme.pdf)

**Comment by freaad** [comment]
Thank you.

**Comment by edmondja** [comment]
I wanted to post the same before I saw your issue x)

**Comment by Nufflee** [comment]
I'm pretty sure it is but not through this "simplified" API. Tello also has a (unofficial?) more advanced and robust API that you can see [here](https://bitbucket.org/PingguSoft/pytello/src/09d98e0e16462180dd487e346d9fabe56238bf16/tello.py?at=master&fileviewer=file-view-default). I think it's the same API used by the app as it has a thing for setting stick values. There's also [this](https://bitbucket.org/PingguSoft/pytello/src/09d98e0e16462180dd487e346d9fabe56238bf16/tello.py?at=master&fileviewer=file-view-default#tello.py-416) very promising function for retrieving video data/feed but I couldn't get it to work. @freaad @edmondja

**Comment by edmondja** [comment]
Hi, thanks for the information.
What did you try to do to get the videos ?
from pytello.tello import Tello
t = Tello()
t.setSmartVideoShot(1, True)
Something like that ?

**Comment by arthursp** [comment]
Yes it's possible, a team created it with golang : https://gobot.io/documentation/examples/tello_opencv/, 
I tried to reverse engineered it to find the utf8 command from the binary uint8[], but not yet found...

**Comment by freaad** [comment]
ok I find the real useful python tello library. I put on the link.
https://github.com/hanyazou/TelloPy
